# Generated by Django 5.0.6 on 2024-06-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
